version: 2

builds:
  - id: openvpn-web
    binary: openvpn-web
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser
archives:
  - formats: ['binary']
    name_template: >-
      openvpn-web-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else if eq .Arch "arm" }}armv{{ .Arm }}l
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'openvpn-web_sha256_checksums.txt'
  algorithm: sha256
upx:
  - enabled: true
